[terminal.shell]
program = "wsl.exe"
args = ["--cd ~"]

[env]
TERM = "xterm-256color"

decorations = "none"

[font]
normal = { family = "Hack Nerd Font Mono", style = "Regular" }
italic = { family = "Hack Nerd Font Mono", style = "Italic" }
bold = { family = "Hack Nerd Font Mono", style = "Bold" }
size = 12

[selection]
save_to_clipboard = true
