onboarding = false
[keys]
prefix = "ctrl+a"
goto = "ctrl+b"

[theme]
name = "catppuccin-latte"
auto_switch = true
light_name = "catppuccin-latte"
dark_name = "gruvbox-dark-hard"

[ui]
agent_panel_sort = "priority"
show_agent_labels_on_pane_borders = false
