onboarding = false

[keys]
prefix = "ctrl+a"

[[keys.command]]
key = "prefix+m"
type = "plugin_action"
command = "spotify-now-playing.open"
description = "Spotify now playing"

[[keys.command]]
key = "prefix+f"
type = "plugin_action"
command = "sessionizer.pick"
description = "Open sessionizer"

[theme]
name = "catppuccin-latte"
auto_switch = true
light_name = "catppuccin-latte"
dark_name = "gruvbox-dark-hard"

[ui]
prompt_new_tab_name = false
agent_panel_sort = "priority"
show_agent_labels_on_pane_borders = false
